--- util/docker.lua
---
--- Resolves the Docker Compose service that owns the PHP file currently
--- being edited, so linting, formatting, testing and debugging all run
--- inside the same container the app actually runs in.
---
--- Design constraints this was built against (see the "why" below, learned
--- the hard way from a previous version of this file that silently fell
--- back to local tools whenever detection failed):
---
---   1. Detection walks UP from the buffer's own directory, never
---      `vim.fn.getcwd()`. A monorepo's docker-compose.yml usually lives at
---      the repo root while you're editing several directories below it --
---      and this is also what makes plain (non-generated-override) git
---      worktrees "just work": a worktree that carries its own full copy
---      of docker-compose.yml (Project B's `_worktrees/<ticket>/`) is found
---      before the walk ever reaches the main checkout's copy.
---   2. Service names are never guessed and used blindly. Every candidate
---      is verified against `docker compose config --format json <name>`
---      before it's trusted -- passing the service name explicitly also
---      sidesteps Compose *profile* gating, which otherwise hides most
---      services from a plain `docker compose config --services`.
---   3. Failure is loud. If a compose project is found near the file but
---      the service can't be pinned down, callers get `false` back and
---      must NOT fall back to running the local/host tool -- that silent
---      fallback (running local PHPStan/PHPUnit instead of the
---      container's) was the actual root cause of "it lints with a config
---      that isn't mine" and "it uses my local PHP".
---
--- Resolution order, first match wins:
---   1. $PHP_DOCKER_SERVICE env var (explicit, always trusted if valid)
---   2. Project A-style generated worktree overlay: a buffer under
---      `.worktrees/<dir>/` whose repo root has a
---      `.worktrees/compose.<ticket>.yml` (generated by Project A's /wt
---      workflow) -- `<dir>`'s ticket prefix is found by trying
---      dash-separated prefixes against real generated files, since a
---      ticket's worktrees can carry a role suffix (`ticket-1203-backend`,
---      `ticket-1203-client`, ...). Resolves to service `<ticket_>_api` with
---      the overlay file layered on top of the base compose file.
---   3. `.nvim-php-docker.json` marker file (`{"service": "name"}`),
---      searched from the buffer's directory up to the compose root --
---      for repos like Project A's main checkout where multiple compose
---      services (`client_api`, `manager_api`, ...) all front the SAME
---      `backend/` directory, so no path-segment convention can pick the
---      one that actually runs PHP (`api`). The marker may also carry an
---      optional `"project_prefix"` for a project whose compose file names
---      its own project dynamically from the checked-out branch (Project C's
---      per-worktree Compose wrapper script computes a `STACK_ID=<prefix>-
---      <branch slug>` per worktree) -- without it, plain `docker compose`
---      falls back to the compose file's default project name and silently
---      targets the wrong (or no) container instead of the worktree's own
---      running stack. See `resolve_project_name` below for the exact slug
---      algorithm, which mirrors that script's. The marker may also carry
---      an optional `"xdebug_port"`, for the moment more than one project
---      debugs concurrently and each needs a distinct Xdebug `client_port`
---      -- see `find_marker_service` below.
---   4. `services/<name>/...` -> `<name>-service` path convention
---      (Project B-style monorepos), walking from the path segment closest
---      to the file toward the compose root.

local M = {}

---@class DockerInfo
---@field root string             directory containing the base compose file
---@field base_file string        the base compose file's name (e.g. "compose.yml")
---@field service string          compose service name
---@field workdir string          the service's working directory inside the container
---@field mount {source:string, target:string}|nil  bind mount covering workdir
---@field compose_files string[]  extra `-f <file>` overlay layers, absolute paths (may be empty)
---@field project_name string|nil  explicit `-p <name>` override (see `resolve_project_name`)
---@field xdebug_port number|nil  explicit Xdebug client_port override (see a marker's "xdebug_port")

local resolve_cache = {}

---@param start_dir string
---@return string|nil root
---@return string|nil base_file
local function find_compose_root(start_dir)
  local markers = { "docker-compose.yml", "docker-compose.yaml", "compose.yml", "compose.yaml" }
  local dir = start_dir
  for _ = 1, 50 do
    for _, marker in ipairs(markers) do
      if vim.fn.filereadable(dir .. "/" .. marker) == 1 then
        return dir, marker
      end
    end
    local parent = vim.fn.fnamemodify(dir, ":h")
    if parent == dir then
      break
    end
    dir = parent
  end
  return nil, nil
end

---@param cmd string[]
---@param cwd string
local function run(cmd, cwd)
  return vim.system(cmd, { cwd = cwd, text = true }):wait()
end

--- Resolve symlinks. Local paths reach this module through more than one
--- route (nvim buffer names vs. `docker compose config`'s reported bind
--- mount `source`), and they don't always agree on which side of a
--- symlink they're phrased from (e.g. `~/projects` -> `/projects`).
--- Comparing/prefix-matching raw strings across those routes silently
--- fails whenever a symlink is involved, so every path that will be
--- compared or prefix-stripped is normalized through this first.
---@param path string
---@return string
local function realpath(path)
  return (vim.uv.fs_realpath(path)) or path
end

--- `-f` flags for a compose invocation. Passing ANY `-f` suppresses
--- Compose's default-file auto-discovery entirely, so the base file must
--- be listed explicitly alongside every overlay -- `-f <overlay>` alone
--- (without the base file) silently drops every service the overlay
--- doesn't redefine.
---@param base_file string|nil
---@param compose_files string[]
---@return string[]
local function compose_file_flags(base_file, compose_files)
  if #compose_files == 0 then
    return {}
  end
  local flags = { "-f", base_file }
  for _, f in ipairs(compose_files) do
    table.insert(flags, "-f")
    table.insert(flags, f)
  end
  return flags
end

--- Probe whether `candidate` is a real compose service under `compose_files`
--- (base file in `root` implicit, plus any extra `-f` layers). Naming the
--- service explicitly bypasses profile gating, so this is reliable
--- regardless of which `profiles:` are active.
---@param root string
---@param base_file string|nil
---@param candidate string
---@param compose_files string[]
---@return table|nil service_config
---@return string|nil error
local function probe_service(root, base_file, candidate, compose_files)
  local cmd = { "docker", "compose" }
  vim.list_extend(cmd, compose_file_flags(base_file, compose_files))
  vim.list_extend(cmd, { "config", "--format", "json", candidate })
  local result = run(cmd, root)
  if result.code ~= 0 then
    return nil, vim.trim(result.stderr or "(no error output)")
  end
  local ok, decoded = pcall(vim.json.decode, result.stdout or "")
  if not ok or not decoded or not decoded.services or not decoded.services[candidate] then
    return nil, "unexpected `docker compose config` output"
  end
  return decoded.services[candidate]
end

--- Find the bind mount covering the service's working_dir, so callers can
--- translate between local and container paths. If the compose file
--- doesn't declare `working_dir:` (common -- it's often left to the
--- image's own Dockerfile `WORKDIR`, which `docker compose config` does
--- NOT surface), fall back to the sole directory bind mount when there's
--- exactly one unambiguous candidate.
---@param service_cfg table
---@return {source:string, target:string}|nil mount
---@return string|nil inferred_workdir  set only when workdir had to be inferred
local function primary_mount(service_cfg)
  local workdir = service_cfg.working_dir
  local dir_mounts = {}
  for _, vol in ipairs(service_cfg.volumes or {}) do
    if vol.type == "bind" and vol.target and vol.source then
      local stat = vim.uv.fs_stat(vol.source)
      if stat and stat.type == "directory" then
        table.insert(dir_mounts, vol)
      end
    end
  end

  if workdir then
    for _, vol in ipairs(dir_mounts) do
      if workdir == vol.target or vim.startswith(workdir .. "/", vol.target .. "/") then
        return { source = realpath(vol.source), target = vol.target }
      end
    end
    return nil
  end

  if #dir_mounts == 1 then
    local vol = dir_mounts[1]
    return { source = realpath(vol.source), target = vol.target }, vol.target
  end

  return nil
end

--- Guess the compose service owning `bufdir`, walking from the path
--- segment closest to the file toward `root`. Each segment is tried as-is
--- and with a "-service" suffix (the `services/<name>` -> `<name>-service`
--- convention). The first candidate Compose actually recognizes wins --
--- nothing is assumed without verifying.
---@param root string
---@param bufdir string
---@return string|nil service
---@return table|string cfg_or_error  service config on success, error string on failure
local function guess_service(root, bufdir)
  local rel = bufdir:sub(#root + 2)
  if rel == "" then
    return nil, "the file is at the compose root; there's no path segment to derive a service name from"
  end
  local segments = vim.split(rel, "/", { plain = true })

  local tried = {}
  for i = #segments, 1, -1 do
    for _, candidate in ipairs({ segments[i], segments[i] .. "-service" }) do
      table.insert(tried, candidate)
      local cfg = probe_service(root, nil, candidate, {})
      if cfg then
        return candidate, cfg
      end
    end
  end

  return nil, "none of these looked like a real compose service: " .. table.concat(tried, ", ")
end

--- Look for a `.nvim-php-docker.json` marker
--- (`{"service": "name", "compose_files": [...], "project_prefix": "...",
--- "xdebug_port": 9003}`), searching from `bufdir` up to (and including)
--- `root`. Closest wins. `compose_files`, `project_prefix` and
--- `xdebug_port` are all optional (omitting all three matches the marker's
--- original, simpler schema).
---
--- `compose_files` exists for a service that only exists once an extra
--- overlay is layered on top of the base compose file, e.g. a custom
--- per-worktree environment set up outside the ticket-numbered /wt
--- workflow, so `project_a_worktree_override` above has no way to find it.
--- Entries are resolved relative to `root` (absolute paths left as-is).
---
--- `project_prefix` exists for a project whose own tooling computes the
--- Compose project name dynamically per worktree (see `resolve_project_name`).
---
--- `xdebug_port` exists for the moment more than one project debugs at
--- once: Xdebug's own default `client_port` (9003) is shared by every
--- project until each is given a distinct one here AND the container's own
--- `xdebug.client_port` ini setting is changed to match -- this only
--- overrides the nvim-dap side, it can't reconfigure the container.
---@param root string
---@param bufdir string
---@return string|nil service
---@return string[]|nil compose_files  absolute paths
---@return string|nil project_prefix
---@return number|nil xdebug_port
local function find_marker_service(root, bufdir)
  local dir = bufdir
  for _ = 1, 50 do
    local marker = dir .. "/.nvim-php-docker.json"
    if vim.fn.filereadable(marker) == 1 then
      local ok, decoded = pcall(vim.json.decode, table.concat(vim.fn.readfile(marker), "\n"))
      if ok and decoded and decoded.service then
        local compose_files = {}
        for _, f in ipairs(decoded.compose_files or {}) do
          table.insert(compose_files, vim.startswith(f, "/") and f or (root .. "/" .. f))
        end
        return decoded.service, compose_files, decoded.project_prefix, decoded.xdebug_port
      end
    end
    if dir == root then
      break
    end
    local parent = vim.fn.fnamemodify(dir, ":h")
    if parent == dir then
      break
    end
    dir = parent
  end
  return nil
end

--- Slugify a branch name the same way Project C's per-worktree Compose
--- wrapper script does, so `resolve_project_name` computes the exact
--- `STACK_ID` that script would export: lowercase, strip a leading
--- `feature|feat|fix|chore/` prefix, collapse any run of non-alnum
--- characters to a single `-`, trim leading/trailing `-`, cap at 30 chars.
---@param branch string
---@return string
local function slugify_branch(branch)
  branch = branch:lower()
  for _, prefix in ipairs({ "feature/", "feat/", "fix/", "chore/" }) do
    if vim.startswith(branch, prefix) then
      branch = branch:sub(#prefix + 1)
      break
    end
  end
  branch = branch:gsub("[^a-z0-9]+", "-"):gsub("^%-+", ""):gsub("%-+$", "")
  return branch:sub(1, 30)
end

--- `<prefix>-<slugified current branch>`, for a marker's `project_prefix`.
--- Returns nil (caller should proceed without a `-p` override) if `root`
--- isn't a git checkout or the branch can't be determined -- this is a
--- best-effort convenience, not something to fail loudly over the way an
--- unresolvable service does.
---@param root string
---@param prefix string
---@return string|nil
local function resolve_project_name(root, prefix)
  local result = run({ "git", "rev-parse", "--abbrev-ref", "HEAD" }, root)
  if result.code ~= 0 then
    return nil
  end
  local branch = vim.trim(result.stdout or "")
  if branch == "" or branch == "HEAD" then
    return nil
  end
  return prefix .. "-" .. slugify_branch(branch)
end

--- Project A-style generated worktree overlay: a buffer under
--- `.worktrees/<dir>/` where `root` has a `.worktrees/compose.<ticket>.yml`
--- generated by the /wt workflow. `<dir>` may carry a role suffix
--- (`proj-1203-backend` -> ticket `proj-1203`), found by trying
--- dash-separated prefixes, longest first, against real generated files.
---@param root string
---@param bufdir string
---@return string|nil service
---@return string[]|nil compose_files
local function project_a_worktree_override(root, bufdir)
  local rel = bufdir:sub(#root + 2)
  local wt_dir = rel:match("^%.worktrees/([^/]+)/")
  if not wt_dir then
    return nil
  end
  local parts = vim.split(wt_dir, "-", { plain = true })
  for i = #parts, 1, -1 do
    local ticket = table.concat(vim.list_slice(parts, 1, i), "-")
    local overlay = root .. "/.worktrees/compose." .. ticket .. ".yml"
    if vim.fn.filereadable(overlay) == 1 then
      local service = "proj_" .. ticket:gsub("^proj%-", ""):gsub("-", "_") .. "_api"
      return service, { overlay }
    end
  end
  return nil
end

--- Resolve Docker project info for the file at `filepath`.
---@param filepath string absolute path of the buffer being edited
---@return DockerInfo|nil|false
---   DockerInfo on success.
---   nil if no compose project was found near this file (use local tools).
---   false if a compose project was found but the service could not be
---   pinned down -- an error was already shown; do NOT fall back to local.
function M.resolve(filepath)
  if filepath == "" then
    return nil
  end
  local bufdir = vim.fn.fnamemodify(filepath, ":p:h")
  local root, base_file = find_compose_root(bufdir)
  if not root then
    return nil
  end

  local cache_key = root .. "|" .. bufdir
  if resolve_cache[cache_key] ~= nil then
    return resolve_cache[cache_key]
  end

  local env_service = os.getenv("PHP_DOCKER_SERVICE")
  local service, cfg_or_err, compose_files
  local project_name, xdebug_port

  if env_service and env_service ~= "" then
    local cfg, err = probe_service(root, base_file, env_service, {})
    if not cfg then
      vim.notify(
        "docker.lua: $PHP_DOCKER_SERVICE=" .. env_service .. " is not valid in " .. root .. ": " .. err,
        vim.log.levels.ERROR
      )
      resolve_cache[cache_key] = false
      return false
    end
    service, cfg_or_err, compose_files = env_service, cfg, {}
  else
    local wt_service, wt_files = project_a_worktree_override(root, bufdir)
    local marker_service, marker_files, marker_project_prefix, marker_xdebug_port
    if not wt_service then
      marker_service, marker_files, marker_project_prefix, marker_xdebug_port = find_marker_service(root, bufdir)
    end

    local candidate_service = wt_service or marker_service
    local candidate_files = wt_files or marker_files or {}

    if candidate_service then
      local cfg, err = probe_service(root, base_file, candidate_service, candidate_files)
      if not cfg then
        vim.notify(
          "docker.lua: resolved service '"
            .. candidate_service
            .. "' for "
            .. filepath
            .. " but Compose rejected it: "
            .. err,
          vim.log.levels.ERROR
        )
        resolve_cache[cache_key] = false
        return false
      end
      service, cfg_or_err, compose_files = candidate_service, cfg, candidate_files
      if marker_project_prefix then
        project_name = resolve_project_name(root, marker_project_prefix)
      end
      xdebug_port = marker_xdebug_port
    else
      local svc, cfg_or_error = guess_service(root, bufdir)
      if not svc then
        vim.notify(
          "docker.lua: couldn't determine the compose service for "
            .. filepath
            .. " ("
            .. cfg_or_error
            .. "). Set $PHP_DOCKER_SERVICE, or add a .nvim-php-docker.json marker with {\"service\": \"name\"}.",
          vim.log.levels.ERROR
        )
        resolve_cache[cache_key] = false
        return false
      end
      service, cfg_or_err, compose_files = svc, cfg_or_error, {}
    end
  end

  local mount, inferred_workdir = primary_mount(cfg_or_err)
  local workdir = cfg_or_err.working_dir or inferred_workdir
  if not workdir then
    vim.notify(
      "docker.lua: service '"
        .. service
        .. "' has no `working_dir` and no single unambiguous bind mount to infer it from; path handling will be unreliable.",
      vim.log.levels.WARN
    )
  end

  local info = {
    root = root,
    base_file = base_file,
    service = service,
    workdir = workdir,
    mount = mount,
    compose_files = compose_files,
    project_name = project_name,
    xdebug_port = xdebug_port,
  }
  resolve_cache[cache_key] = info
  return info
end

--- Translate a local absolute path to its container path, using the
--- resolved bind mount. Falls back to the input path if there's no mount
--- info (e.g. the local path is returned as-is, which is at least a
--- sane failure mode: the container-side command will just fail loudly
--- with a "file not found" instead of silently touching the wrong file).
---@param info DockerInfo
---@param local_path string
---@return string
function M.to_container_path(info, local_path)
  local real = realpath(local_path)
  if info.mount and vim.startswith(real, info.mount.source .. "/") then
    return info.mount.target .. real:sub(#info.mount.source + 1)
  end
  return local_path
end

--- Translate a container absolute path back to its local (realpath'd)
--- path -- compare the result against a realpath'd local path, not a raw
--- buffer name, or a symlink in the way (e.g. `~/projects` -> `/projects`)
--- will make an identical file look like a mismatch.
---@param info DockerInfo
---@param container_path string
---@return string
function M.to_local_path(info, container_path)
  if info.mount and vim.startswith(container_path, info.mount.target .. "/") then
    return info.mount.source .. container_path:sub(#info.mount.target + 1)
  end
  return container_path
end

--- `-p <name>` (when `info.project_name` is set, e.g. via a marker's
--- `project_prefix`) plus `-f <file>` flags for `info.compose_files`, for
--- callers building a raw `docker compose ...` command (e.g.
--- `{"compose", unpack(docker.compose_flags(info)), "exec", ...}`).
---@param info DockerInfo
---@return string[]
function M.compose_flags(info)
  local flags = {}
  if info.project_name then
    vim.list_extend(flags, { "-p", info.project_name })
  end
  vim.list_extend(flags, compose_file_flags(info.base_file, info.compose_files or {}))
  return flags
end

--- Public realpath helper -- callers translating paths for comparison
--- (e.g. matching a tool's reported file path against the current buffer)
--- need the same symlink-normalization `resolve`/`to_local_path` use
--- internally, see the `realpath` local above for why.
---@param path string
---@return string
function M.realpath(path)
  return realpath(path)
end

function M.clear_cache()
  resolve_cache = {}
end

vim.api.nvim_create_user_command("PhpDockerRefresh", function()
  require("util.docker").clear_cache()
  vim.notify("docker.lua: cache cleared, next lint/format/test/debug will re-resolve", vim.log.levels.INFO)
end, { desc = "Clear cached Docker Compose service resolution" })

vim.api.nvim_create_autocmd("DirChanged", { callback = M.clear_cache })

return M
